"""initial migration for Codebase

Revision ID: 31d392c53a99
Revises: 
Create Date: 2026-01-16 13:27:29.401967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d392c53a99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codebases',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.Enum('zip', 'github_url', name='source_type'), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='codebase_status'), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('processed_files', sa.Integer(), nullable=False),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('all_languages', sa.JSON(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.String(length=255), nullable=True),
    sa.Column('secrets_detected', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codebases_name'), 'codebases', ['name'], unique=False)
    op.create_index(op.f('ix_codebases_status'), 'codebases', ['status'], unique=False)
    op.create_index(op.f('ix_codebases_workflow_id'), 'codebases', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_codebases_workflow_id'), table_name='codebases')
    op.drop_index(op.f('ix_codebases_status'), table_name='codebases')
    op.drop_index(op.f('ix_codebases_name'), table_name='codebases')
    op.drop_table('codebases')
    # ### end Alembic commands ###
